### ISSUE TITLE
Add an option to select the ABCI port 

### ISSUE THREAD

**Issue by Galadrin** [KYVENetwork/supervysor#1]
The endpoint for query the node progress is mandatory as defined in the constant. 
https://github.com/KYVENetwork/supervysor/blob/a84e13b2395b9e51aa6908c026ea998190eb4db3/types/constants.go#L4

it could be nice to be able to have a parameter to customise it.

**Comment by christopherbrumm** [comment]
Added in [_update: support custom ABCI Endpoint._](https://github.com/KYVENetwork/supervysor/commit/2cec613ae2040bdb9b280e6f3fb7737eaa2e9222)
